---
- name: playbook to install firefox
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/firefox.yml

  tasks:
    - include_tasks: debian/firefox-playbook.yml
      when: ansible_facts["distribution"] == 'Debian' or ansible_facts["distribution"] == 'Ubuntu'

    - include_tasks: fedora/firefox-playbook.yml
      when: ansible_facts["distribution"] == 'Fedora'
