---
- name: playbook to install helm
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/helm.yml

  tasks:
    - name: Check current helm version
      command: helm version --client
      register: helm_vsn
      changed_when: false
      failed_when: false
      check_mode: no

    - set_fact:
        helm_current_version: "{{ helm_vsn.stdout | regex_search('(v\\d+(\\.\\d+)+)') }}"
      when:
        - helm_vsn.stdout is defined

    - name: Download and decompress Helm
      unarchive:
        src: 'https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz'
        dest: '/tmp'
        remote_src: yes
      when: >
        helm_current_version is not defined
        or helm_current_version is version(helm_version, '!=')

    - name: Copy helm
      become: true
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        mode: 'a+x'
        force: yes
      when: >
        helm_current_version is not defined
        or helm_current_version is version(helm_version, '!=')
