---
- name: playbook to install postman latest version
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/postman.yml

  tasks:
    - name: Check if postman is installed
      stat:
        path: /usr/local/bin/postman
      register: postman_stats

    - name: Download postman
      get_url:
        url: '{{ mirror }}'
        dest: '{{ download_dir }}/{{ download_filename }}'
        mode: 'u=rw,go=r'
      when: not postman_stats.stat.exists

    - name: Create download directory installation
      file:
        dest: '{{ local_dir }}'
        state: directory

    - name: Extract postman files
      unarchive:
        remote_src: yes
        src: '{{ download_dir }}/{{ download_filename }}'
        dest: '{{ download_dir }}'
      when: not postman_stats.stat.exists

    - name: Copy files to local dir
      copy:
        src: '{{ download_dir }}/Postman/'
        dest: '{{ local_dir }}'
      when: not postman_stats.stat.exists

    - name: Fix postman scripts permissions
      file:
        path: '{{ local_dir }}'
        recurse: yes
        mode: 'u=rwx,go=rx'

    - name: Create symbolic link
      become: true
      file:
        src: "{{ local_dir }}/app/Postman"
        dest: "/usr/local/bin/postman"
        state: link
        mode: '0755'
