---
- name: playbook to install thefuck
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/thefuck.yml

  tasks:
    - name: Install dependencies
      become: yes
      apt:
        name:
          - python3-dev
          - python3-pip
          - python3-setuptools
        state: present
        update_cache: no

    - name: Install thefuck
      become: yes
      pip:
        name: thefuck

    - name: Check if exist bash aliass
      command: 'grep -F "thefuck" {{ bashrc_path }}'
      register: thefuck_alias

    - set_fact:
        thefuck_current_alias: '{{ thefuck_alias.stdout }}'
      when:
        - thefuck_alias.stdout is defined

    - name: Add thefuck alias
      lineinfile:
        path: '{{ bashrc_path }}'
        line: '{{ thefuck_command }}'
      when:
        - thefuck_current_alias == thefuck_command
