---
- name: playbook to install thefuck
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/thefuck.yml

  tasks:
    - include_tasks: debian/thefuck-playbook.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - include_tasks: fedora/thefuck-playbook.yml
      when: ansible_distribution == 'Fedora'
