---
- name: playbook to install zoom
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/zoom.yml

  tasks:
    - name: Install required pakcages
      become: yes
      apt:
        name:
          - libglib2.0-0
          - libgstreamer-plugins-base1.0-0
          - libxcb-shape0
          - libxcb-shm0
          - libxcb-xfixes0
          - libxcb-randr0
          - libxcb-image0
          - libfontconfig1
          - libgl1-mesa-glx
          - libxi6
          - libsm6
          - libxrender1
          - libpulse0
          - libxcomposite1
          - libxslt1.1
          - libsqlite3-0
          - libxcb-keysyms1
          - libxcb-xtest0
        state: present
        update_cache: no

    - name: Check if zoom is installed
      become: yes
      command: dpkg-query -W zoom
      register: zoom_check_deb
      failed_when: zoom_check_deb.rc > 1
      changed_when: zoom_check_deb.rc == 1

    - name: Download zoom
      become: yes
      get_url:
        url: '{{ zoom_url }}'
        dest: '{{ zoom_deb_dest }}'
      when: zoom_check_deb.rc == 1

    - name: Install zoom
      become: yes
      apt:
        deb: '{{ zoom_path }}'
      when: zoom_check_deb.rc == 1
